### ISSUE TITLE
SEQUEL DEPRECATION WARNING: Calling a dataset filtering method with a plain string is deprecated and will be removed in Sequel 5

### ISSUE THREAD

**Issue by FayeFang** [contentful/contentful-database-importer.rb#12]
Getting the deprecation error below when using `self.query = ' option.

```
SEQUEL DEPRECATION WARNING: Calling a dataset filtering method with a plain string is deprecated and will be removed in Sequel 5.  Use Sequel.lit("url = 'ddd'") to create a literal string and pass that to the dataset filtering method, or use the auto_literal_strings extension.
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sequel-4.47.0/lib/sequel/dataset/query.rb:1315:in `filter_expr'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sequel-4.47.0/lib/sequel/dataset/query.rb:1249:in `add_filter'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sequel-4.47.0/lib/sequel/dataset/query.rb:1034:in `where'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-database-importer-0.3.2/lib/contentful/database_importer/resource_class_methods.rb:73:in `all'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-database-importer-0.3.2/lib/contentful/database_importer/json_generator.rb:41:in `create_entries'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-database-importer-0.3.2/lib/contentful/database_importer/json_generator.rb:14:in `block in generate_json'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-database-importer-0.3.2/lib/contentful/database_importer/json_generator.rb:11:in `each'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-database-importer-0.3.2/lib/contentful/database_importer/json_generator.rb:11:in `generate_json'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-database-importer-0.3.2/lib/contentful/database_importer.rb:33:in `generate_json'
```

Tried to pass in `self.query = Sequel.lit("url = 'ddd'")` and got the same error. Help!

Also, passing in a namespaced table as`self.table_name = 'namespace.table'` is not working. Help please!

**Comment by dlitvakb** [comment]
Hey @FayeFang,

As for the deprecation warning, I can either lock the version to `~> 4.0` or add a comment explaining how to use `Sequel::lit`, though I never personally used it, so it may require a bit of digging.

As for the `namespace.table` issue, please try doing `namespace__table` (that's a double underscore), it's how Sequel deals with Schema definitions.

Cheers

**Comment by FayeFang** [comment]
@dlitvakb great thanks! Sequel.lit works on my side. Explanation on the page will be great for future reference!

for namespace, double_underscore works but it gives a deprecation warning below
```SEQUEL DEPRECATION WARNING: Symbol splitting is deprecated and will be removed in Sequel 5.  Either set Sequel.split_symbols = true, or change :namespace__table to Sequel.qualify("namespace", "table").```

However, if I change it to `Sequel.qualify("namespace", "table")`, I get another error below

```/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-database-importer-0.3.2/lib/contentful/database_importer/resource_class_methods.rb:9:in `table_name': undefined method `to_sym' for #<Sequel::SQL::QualifiedIdentifier:0x007fc2034e1228> (NoMethodError)
Did you mean?  to_s```

Let me know what you think!

**Comment by dlitvakb** [comment]
Hey @FayeFang,

The error when using `Sequel.qualify` is due to how the gem accepts strings, I will look for a way to implement `Sequel::qualify`.

I'll let you know as soon as I get more details.

Cheers

**Comment by dlitvakb** [comment]
Ok, just tested these things, and added the corresponding comments on each of the sections explaining how to use this gem if using Sequel `v5`. https://github.com/contentful/contentful-database-importer.rb/commit/25e2734b7518a4e2505de92cf39ae73d09dbe8e6

Cheers

**Comment by FayeFang** [comment]
Great! Everything works now :)
