### ISSUE TITLE
Split a table field into multiple contentful fields

### ISSUE THREAD

**Issue by FayeFang** [contentful/contentful-database-importer.rb#13]
I have a table field with type hstore and want to split into multiple contentful fields with some pre-processing. However, only the first contentful field is outputted.

For example:
```ruby
  field :field, maps_to: :field1, type: :string, pre_process: -> (value) {  #do the work }
  field :field, maps_to: :field2, type: :string, pre_process: -> (value) {  #do the work }
  field :field, maps_to: :field3, type: :string, pre_process: -> (value) {  #do the work }
```
only `field1` is being generated.

Is there an option for it? Thanks!

**Comment by dlitvakb** [comment]
Hey @FayeFang,

I would use a JSON `:object` field type instead. As of currently, the only way to determine how to process a field is by checking it's column name, having many definitions matching the column name would certainly make it to fetch the first one only.

I'm thinking that it may be possible to have multiple field definitions, but I would have to add that as an additional feature.

Please let me know if this is something you'd like, and I'll add it to my backlog.

Cheers

**Comment by FayeFang** [comment]
Hi,

Thanks for the reply! I think that is a nice to have feature. But I am able to get my way around it for now. 

Thanks again!

**Comment by dlitvakb** [comment]
No problem!

We'll add it to the backlog.

Cheers

**Comment by FayeFang** [comment]
@dlitvakb Found a typo in the README: 
```field :quxs, type: Qux, relationship: :many_through, through: :foo_qux, primary_id_field: :id, primary_key: :foo_id, foreign_key: :qux_id, foreign_id_field: :id```
should be 
```field :quxs, type: Qux, relationship: :through, through: :foo_qux, primary_id_field: :id, primary_key: :foo_id, foreign_key: :qux_id, foreign_id_field: :id```

the relevant method is `fetch_through_relationship_options`.

**Comment by FayeFang** [comment]
@dlitvakb Question on actual importing.

When I try to import a data set with more than 500 entries, I would get errors like below but there is nowhere for me to trace it back:

```/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-management-1.8.0/lib/contentful/management/client.rb:256:in `execute_request': Validation error (Contentful::Management::UnprocessableEntity)
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-management-1.8.0/lib/contentful/management/client.rb:321:in `put'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-management-1.8.0/lib/contentful/management/request.rb:52:in `put'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-management-1.8.0/lib/contentful/management/resource_requester.rb:80:in `put'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-management-1.8.0/lib/contentful/management/resource_requester.rb:38:in `update'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-management-1.8.0/lib/contentful/management/resource.rb:66:in `update'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful_bootstrap-3.6.1/lib/contentful/bootstrap/templates/base.rb:195:in `block in create_entries'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful_bootstrap-3.6.1/lib/contentful/bootstrap/templates/base.rb:190:in `map'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful_bootstrap-3.6.1/lib/contentful/bootstrap/templates/base.rb:190:in `create_entries'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful_bootstrap-3.6.1/lib/contentful/bootstrap/templates/base.rb:20:in `run'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful_bootstrap-3.6.1/lib/contentful/bootstrap/commands/update_space.rb:51:in `update_json_template'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful_bootstrap-3.6.1/lib/contentful/bootstrap/commands/update_space.rb:29:in `run'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful_bootstrap-3.6.1/lib/contentful/bootstrap/command_runner.rb:23:in `update_space'
	from /Users/fayefang/personal-projects/contentful-database-importer.rb/lib/contentful/database_importer.rb:57:in `bootstrap_update_space!'
	from /Users/fayefang/personal-projects/contentful-database-importer.rb/lib/contentful/database_importer.rb:73:in `update_space!'
	from import.rb:25:in `<main>'
```

I tried `Contentful::DatabaseImporter.generate_json!` to see if I can trace the errors but I can get valid results from this call.

Is there a way to trace errors and fix this exception?

**Comment by dlitvakb** [comment]
Currently the only way to check these errors is by looking into the dataset and debugging with the dataset directly.

Please open an issue here: https://github.com/contentful/contentful-bootstrap.rb so that I can add it to our backlog.

Cheers
