### ISSUE TITLE
Specify language when importing data

### ISSUE THREAD

**Issue by johnnyhansson** [contentful/contentful-database-importer.rb#15]
Hi,

Lets say I have a content model containing fields which uses the localization feature in Contentful. 
Is it possible to specify the language when uploading data to  Contentful using this tool?

**Comment by dlitvakb** [comment]
Hi @johnnyhansson,

This is not something that we currently support.

I'll escalate this as a feature request to our PMs and get back to you as soon as I can.

Cheers

**Comment by dlitvakb** [comment]
This has been added on the latest release.

Cheers
