### ISSUE TITLE
Documentation assumes the user has the bundler gem installed

### ISSUE THREAD

**Issue by keithws** [contentful/contentful-database-importer.rb#5]
For people that have never used ruby, or have not used ruby recently, the documentation in the README tells the user to run:

`bundle exec ruby import.rb`

A person who has not installed the bundler gem will get an error.

**Comment by keithws** [comment]
Note, I also had to add `gem 'pg'` to my Gemfile to connect to my PostgresSQL database. This should also be documented.

**Comment by keithws** [comment]
I also had to add the name of my database to the database connection configuration:

`config.database_connection = 'postgres://user:pass@host:port/database'`

**Comment by dlitvakb** [comment]
Hey @keithws,

Thanks for the comments, I will try to improve the readme.

Cheers

**Comment by dlitvakb** [comment]
Regarding the Postgres connection string, that's specified in the documentation in the bit specific to each database https://github.com/contentful/contentful-database-importer.rb/blob/master/README.md#configuration.

Updating the Gemfile requirements

**Comment by dlitvakb** [comment]
Readme updated, closing this issue.

Please let me know if you have any other concern.

Cheers
